name: flynoclip
version: '1.0-SNAPSHOT'
main: me.carlos.flynoclip.Flynoclip
api-version: '1.21'
authors: [carlos]
description: primeira tentativa de plugin. -> fly e noclip
commands:
  jogar:
    description: joga.
  fly:
    description: toggle fly.
  noclip:
    description: toggle noclip.
  inventory:
    description: ver o inventario de pequeno coagulo.
  god:
    description: god tier.